### ISSUE TITLE
Messages posted but never seen

### ISSUE THREAD

**Issue by habilinour** [MetPX/sarracenia#318] opened 2020-03-08 21:18 UTC
We have seen many cases where messages have been posted by sr_watch but sr_sarra  has never seen them. This issue seems to happen with the release 2.20.02b3.

**Comment by habilinour** [comment] 2020-03-08 21:28
The rabbitmq GUI showed the queue had some unacked messages and it did never go down to zero.

**Comment by petersilva** [comment] 2020-03-10 01:16
looks like similar to #314

**Comment by petersilva** [comment] 2020-03-10 09:48
is the the GFA thing?

**Comment by habilinour** [comment] 2020-03-10 11:52
Yes, it's the GFA thing and the same issue happens with other products.

**Comment by petersilva** [comment] 2020-03-11 07:20
This is happenning on Ubuntu 18.04?

**Comment by habilinour** [comment] 2020-03-11 13:21
Yes,  it's  on Ubuntu 18.04

**Comment by petersilva** [comment] 2020-03-17 13:51
2.18.10b2? is OK.  so need to do a git bisect... need to fix sr_insects to understand how to do that.

**Comment by petersilva** [comment] 2020-04-25 15:40
from events following, likely source is inconsistencies queue definitions causing inconsistent bindings, so queues not getting the messages because the bindings are incorrectly set.  Not a bug, but an effect of time on complex deployment.

likely fixing #324 will prevent this from happenning. in future.

**Comment by petersilva** [comment] 2020-08-31 19:20
given all the system fixes (SAN issues), the fix to the expire settings for consistency, and the upgrade of the software on the cluster to the latest version addressing all issues raised.  closing this issue.

**Closed by petersilva** 2020-08-31 19:20 UTC
Labels: Priority 1 - ASAP
