### ISSUE TITLE
Permission problems in directory creations on FTP/SFTP transfers

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#1218] opened 2024-09-11 13:09 UTC
# How to reproduce the problem

- Create a sender config with SFTP transfer. Set `permDirDefault` to `777`.
- Doing a `sr3 show` of the sender config shows the correct octal value , `511` octal = `777` base 10.
- `permCopy` is also set to false (FYI I also tested with it set to true) 

```
sr3d show sender/my-sender | grep perm
'permCopy': False,
'permDefault': 0,
'permDirDefault': 511,
'permLog': 384,
```

- When a file gets sent, the debug logs show that the destination directory will get `cd_forced` into `775` permissions.

```
2024-09-11 12:40:31,768 [DEBUG] sarracenia.flow send sftp_transport sendTo: sftp://sarra@my-server/
2024-09-11 12:40:31,768 [DEBUG] sarracenia.flow send sftp_transport send /datalocal/sarra/tar_gzip_conversion/ThunderstormOutlook/20240911 20240910T1700Z_MSC_ThunderstormOutlook_OSPC_ON_PT036H0

2024-09-11 12:40:31,769 [DEBUG] sarracenia.flow send sftp_transport send connects
2024-09-11 12:40:31,769 [DEBUG] sarracenia.transfer __init__ class=Sftp , subclasses=[<class 'sarracenia.transfer.file.File'>, <class 'sarracenia.transfer.ftp.Ftp'>, <class 'sarracenia.transfer
 <class 'sarracenia.transfer.sftp.Sftp'>]
2024-09-11 12:40:31,769 [DEBUG] sarracenia.transfer.sftp __init__ sr_sftp __init__
2024-09-11 12:40:31,770 [DEBUG] sarracenia.transfer.sftp connect sr_sftp connect sftp://sarra@my-server/
2024-09-11 12:40:31,984 [DEBUG] sarracenia.transfer.sftp connect sr_sftp connect setting timeout 60.000000
2024-09-11 12:40:31,985 [DEBUG] sarracenia.flow send sftp_transport send cd to /datalocal/sarra/tar_gzip_conversion/ThunderstormOutlook/20240911
2024-09-11 12:40:31,985 [DEBUG] sarracenia.transfer.sftp cd_forced sr_sftp cd_forced 775 /datalocal/sarra/tar_gzip_conversion/ThunderstormOutlook/20240911
2024-09-11 12:40:31,993 [DEBUG] sarracenia.flow send hasattr=True, thresh=0, len=177888, remote_off=0, local_off=0
2024-09-11 12:40:31,993 [DEBUG] sarracenia.transfer.sftp put sr_sftp put 20240910T1700Z_MSC_ThunderstormOutlook_OSPC_ON_PT036H00M_v1.json 20240910T1700Z_MSC_ThunderstormOutlook_OSPC_ON_PT036H00
 0 0
2024-09-11 12:40:31,994 [DEBUG] sarracenia.transfer readlocal_write sr_proto readlocal_write
2024-09-11 12:40:31,994 [DEBUG] sarracenia.transfer local_read_open sr_proto local_read_open getcwd=/apps/sarra/public_data/20240910/MSC-DMS-OP/NINJO-EXPORT/PWB/Thunderstorm/ospc self.cwd=/data
_gzip_conversion/ThunderstormOutlook/20240911
2024-09-11 12:40:31,994 [DEBUG] sarracenia.transfer read_write sr_proto read_write
2024-09-11 12:40:32,005 [DEBUG] sarracenia.transfer.sftp rename sr_sftp rename 20240910T1700Z_MSC_ThunderstormOutlook_OSPC_ON_PT036H00M_v1.json.tmp 20240910T1700Z_MSC_ThunderstormOutlook_OSPC_O
json
2024-09-11 12:40:32,005 [DEBUG] sarracenia.transfer.sftp delete sr_sftp rm 20240910T1700Z_MSC_ThunderstormOutlook_OSPC_ON_PT036H00M_v1.json
2024-09-11 12:40:32,006 [DEBUG] sarracenia.transfer.sftp chmod sr_sftp chmod 664 20240910T1700Z_MSC_ThunderstormOutlook_OSPC_ON_PT036H00M_v1.json
2024-09-11 12:40:32,007 [INFO] sarracenia.flow send Sent: /apps/sarra/public_data//20240910/MSC-DMS-OP/NINJO-EXPORT/PWB/Thunderstorm/ospc/20240910T1700Z_MSC_ThunderstormOutlook_OSPC_ON_PT036H00M_v1.json  into /datalocal/sarra/tar_gzip_conversion/ThunderstormOutlook/20240911/20240910T1700Z_MSC_ThunderstormOutlook_OSPC_ON_PT036H00M_v1.json 0-177887
```

- The remote directory got created with `775` permissions

```
drwxrwxr-x 2 sarra sarra   86 Sep 11 12:40 20240911/
```

- The SFTP source code shows that the message displayed by the logs is wrong. `perm` is never used in the method.
- Also `mkdir` is accompanied with `self.o.permDirDefault` which has `511` octal value.

https://github.com/MetPX/sarracenia/blob/7181508ae12af0085734372d22897a24f79cdfd8/sarracenia/transfer/sftp.py#L95-L129

 Why is the remote directory not getting created with the correct permissions? [paramiko documentation](https://docs.paramiko.org/en/latest/api/sftp.html#paramiko.sftp_client.SFTPClient.mkdir) states that octal values should be used for the `mkdirs` method

**Comment by petersilva** [comment] 2024-09-11 13:16
Fixing this should be a matter of adding a chmod in the right place in the code (naturally surrounded by try: finally for the timers.) It should be a handful of lines of code.

**Comment by petersilva** [comment] 2024-09-11 13:25
looked at the source... sure enough, in flow/__init__() in a couple of places in download and send there are literal 775's...

```

                   logger.debug( f"missing destination directories, makedirs: {msg['new_dir']} " )
                    self.worklist.directories_ok.append(msg['new_dir'])
                    os.makedirs(msg['new_dir'], 0o775, True)
  
    .
   .
   .
   this would be the sending part:
                        self.proto[self.scheme].cd_forced(
                            775, new_dir + '/' + options.inflight)
                        self.proto[self.scheme].cd_forced(775, new_dir)

```

It's probably just a matter of replacing 775 (which is wrong anyways... it will be interpreted as decimal) with permDirDefault... in a couple of places.

**Comment by andreleblanc11** [comment] 2024-09-11 13:27
Right, but that `775` value doesn't get translated to the `mkdir` from `cd_forced`. It uses `self.o.permDirDefault` instead

The `775` is never actually used

https://github.com/MetPX/sarracenia/blob/7181508ae12af0085734372d22897a24f79cdfd8/sarracenia/transfer/sftp.py#L94-L132

**Comment by andreleblanc11** [comment] 2024-09-11 13:32
I think the problem is tied to the `umask` setting that is set on the remote SFTP server.

I just did a test on dev. `umask` of my server is set to `0022`

```python3
>>> sftp.mkdir('test',511)
```

Output

```
drwxr-xr-x    2 leblanca leblanca   4096 Sep 11 13:29 test/
```

This also matches the umask that is set on the remote server for my use case.

```
sarra@goc-dx1:~$ umask
0002
```

```
drwxrwxr-x 2 sarra sarra   86 Sep 11 12:40 20240911/
```

**Comment by andreleblanc11** [comment] 2024-09-11 13:33
From the paramiko documentation.

> mkdir(path, mode=511)
Create a folder (directory) named path with numeric mode mode. The default mode is 0777 (octal). On some systems, mode is ignored. **Where it is used, the current umask value is first masked out**.

**Comment by petersilva** [comment] 2024-09-11 13:35
um... yeah... that's a weakness of sftp.  As a client, there is no way to set the umask, so you are stuck with it.  That's not a bug... that's a properly of sftp.

**Comment by petersilva** [comment] 2024-09-11 13:35
but chmod should still work.

**Comment by petersilva** [comment] 2024-09-11 13:36
the sftp server can set the umask in sshd_config... hmm...

**Comment by andreleblanc11** [comment] 2024-09-11 13:37
yeah looks like it works

```python3
>>> sftp.chmod('test',511)
```
```
drwxrwxrwx    2 leblanca leblanca   4096 Sep 11 13:29 test/
```

**Comment by petersilva** [comment] 2024-09-11 15:43
* we have places in the source code where 775 does not have the octal prefix... however...
* those places typically should not be passing mode bits... instead, should use the instance variable self.o.permDirDefault.
* likely all protocols should ensure that *mkdir* results in a directory with permDirDefault permissions.
 (so chmod integrated inside mkdir.)
* cd_forced should do likewise.  (call signature should not have permissions)
* also in sftp.mkdir ... the actual mkdir is outside the try/except finally... should be patched.
* need to patch ftp, sftp...not sure what else.

**Comment by andreleblanc11** [comment] 2024-09-13 18:30
https://github.com/MetPX/sarracenia/pull/1220 is the PR that got merged for this issue

**Closed as completed** 2024-09-16 17:04 UTC
Labels: good first issue, likely-fixed, v3, Priority 4 - Strategic
