### ISSUE TITLE
odd discard behaviour when using on_file

### ISSUE THREAD

**Issue by tomkralidis** [MetPX/sarracenia#353] opened 2020-08-17 18:42 UTC
Using MetPX 2.20.02b1 with the following config:

```
vbroker amqps://anonymous:anonymous@dd.weather.gc.ca/
queue_name q_${BROKER_USER}.${PROGRAM}.${CONFIG}.${HOSTNAME}

subtopic observations.swob-ml.#
instances 2

mirror True

discard on

on_file /my/python-script.py

directory /tmp/obs
accept .*
```

Results in files not being removed from the `directory` directive of `/tmp/obs`.

When commenting out the `on_file` directive, files are deleted as expected, but any directories created (at any level of nesting within the `directory` directive) are not deleted.

The goal is to be able to receive files, run them through a Python script, and discard accordingly.

**Comment by tomkralidis** [comment] 2020-08-17 19:04
Update: issue for files hanging around was open file handles in `on_file` script.  Fixed and files are now deleted as expected, but not directories as specific above.

**Comment by petersilva** [comment] 2020-08-17 19:52
mirror True is to create the directory tree... If you do not want the directory tree created, then:

`mirror off
`
could also have an on_message that sets new_dir to '/tmp/obs' so that all files are created in that directory, and no other.  Do you need the directory tree as part of your on_file processing?

**Comment by tomkralidis** [comment] 2020-08-17 20:30
Thanks.  In our use case, we need the directory tree in that it helps us (our generic handlers) decide how to process the data.

**Comment by petersilva** [comment] 2020-08-17 22:24
would this be helpful?

https://github.com/MetPX/sarracenia/blob/master/doc/sr_subscribe.1.rst#flatten-string-default

you set:

`flatten _
`
and it will put an _ where it would have put a / before. you then parse the much longer file name.  If you have file names that are too long (> 255 characters) this will not work.  

We can add functionality to do what you want.  My first thought is just when we unlink a file, we just also try to rmdir the containing directory and work our way upwards until it hits one that isn't empty... but all that directory creation and reaping is going to be expensive... especially if many files are in the same directory.  It may slow down processing a lot.

Need to think of a better implementation... one that waits... say, a few minutes before trying to remove the dirs.
not trivial, but should be much cheaper than naive idea above.

**Comment by tomkralidis** [comment] 2020-08-17 23:12
That may not work given our data handlers are searching for `observations/swob-ml` type thing, and for files with, say, `_`, already in the filename there might be some unintended impacts.  In the meantime, as a workaround, we can have a cron wipe empty directories for now.

**Comment by petersilva** [comment] 2021-10-03 17:10
you can use a delimiter other than _, like : or ; or a unicode character like  §  ... so you put 
```
flatten  §
```
and then you can use split('§') in your python code to get identification of all the directories that would have been created.  If you insist on having all directories created, it will be extemely inefficient and slow to be creating and deleting entire trees of directories for every file (and n times slower, where n is the number of directories to create for each file.) so answering your request means creating a cache of directories, and using a periodic process to see which directories have not been recently accessed, and are empty, and then deleting them... 
Even doing that, it will be far more efficient to use flatten, because it avoids directory creation to have a string to parse.  The only caveat is if you have paths that end up longer than 255... flatten might not be an option.

Will write a plugin for v3 to do directory removal (with above.)
but it will be a while.

**Comment by petersilva** [comment] 2021-10-07 11:50
ok, got a copy of the the plugin code being used. the last line of it was:
https://github.com/ECCC-MSC/msc-pygeoapi/blob/master/msc_pygeoapi/event.py

The last line is:
```
self.on_message = self.on_file = event.dispatch  # noqa
```
which assigns the event.dispatch routine to be called whenever a message is received, or when a file is downloaded.  Now the downloading of a file is always preceeded by receipt of a corresponding message.
So event.dispatch for files was being called twice, the first time it was called, the file might not be there,
so try/except in the routine would trigger a return False.  

Sarracenia stops processing a message if a plugin returns False, and the deletion is, naturally a later step.  So any file for which processing fails will not be deleted.

So the non-deletion of files was caused by failing to process files because the dispatcher was being called before the files arrived.  The client re-factored to have one dispatcher for file reception, and a separate for message reception, and that solved the issue.

so... there is no bug... still puzzling over whether more documentation will help...

**Comment by petersilva** [comment] 2021-10-31 15:35
closing this one in favour of #424.

**Closed by petersilva** 2021-10-31 15:35 UTC
Labels: enhancement, help wanted, invalid, NewUseCase, v3only
