### ISSUE TITLE
sr_watch dies after isAlive returns false from the hb_pulse plugin

### ISSUE THREAD

**Issue by EricFunk** [MetPX/sarracenia#236] opened 2019-07-29 13:08 UTC
Here is what seems to be occurring:

1. Heartbeat is triggered after a posting in sr_watch
2. hb_pulse is triggered automatically, it runs a 'parent.publisher.isAlive()' which is returning false for an unknown reason
3. hb_pulse runs:

parent.close()
parent.connect()

which breaks sr_watch because the close() function stops the sr_watch observer, but the connect() method doesn't ever start it up again resulting in a process that continues to run, but doesn't actually watch a directory anymore

**Comment by petersilva** [comment] 2019-07-29 19:46
I remember at some point we had the pulse code added because connectivity was weird.  You have a client, who goes through multiple firewalls that do NAT, and the load balancer that does the same, and they clean out their NAT tables after a period of time, regardless of whether the connection has been terminated, leaving both ends thinking they were still connected, but something in the middle breaking the connection silently, so there was 

 So we added application level pulses to re-establish connections... but then I recall @michelgrenier saying that we didn't need it at some point, because he found something in AMQP that does it for us... but it was already there... so the answer might be to remove pulses entirely...

**Comment by petersilva** [comment] 2019-07-29 19:47
might just add a flag (pulse on|off) for now, and turn it off for testing purposes @habilinour should be aware.

**Comment by benlapETS** [comment] 2019-07-30 14:18
It is normal that isAlive() returns false, because isAlive() doesn't exists anymore. It has been rename to is_alive() to respect snake case naming standard for python method.

**Comment by petersilva** [comment] 2019-07-30 15:27
please determine what version is in use.

**Comment by petersilva** [comment] 2019-07-30 20:09
The version in use is 2.19.04b2, which is the last version published.  the change to isAlive isn´t in any released version.  so the next step would be to reproduce the problem with the same version of the code, somewhere else.

**Comment by petersilva** [comment] 2019-07-30 21:08
oh man, this is weird... just looked in the code... there is isAlive in sr_amqp.py in the Publisher, and another one in sr_consumer, and, of course, they are different.  Do we know which one is being called?
it looks like there is one for a subscriber, and another one for posting, so hopefully it is the one in sr_amqp/Publisher ...

**Comment by petersilva** [comment] 2019-09-22 14:06
while we found a work-around for Eric's deployment.  We need to be sure we have swatted this bug.

**Comment by petersilva** [comment] 2020-04-07 20:10
removed pulse support: commit: 43d991baeaa8b4b7580e8b30624b24d0fda9e1e6

**Comment by petersilva** [comment] 2020-04-14 02:53
v2.20.04b2 contains above patch. should address this issue.

**Comment by petersilva** [comment] 2020-04-28 00:30
It looks like rabbitmq people addressed problem addressed by pulse at the protocol level:

https://www.rabbitmq.com/heartbeats.html

and since we switched to 0.9.1 with the change from amqplib -> amqp.  the application already has these features when the broker is >= 3.6.

The only sad thing is that they named it heartbeats, whereas sarracenia uses the word heartbeats for something else... but this means we will never re-introduce pulse.

**Comment by petersilva** [comment] 2020-04-28 02:21
3a1bc2f63fc10985faa435ebf305835de6ef0a1e more removal of now dead pulse code.

**Closed** 2020-08-31 19:25 UTC
Labels: Priority 2 - Critical, bug, likely-fixed, regression
