### ISSUE TITLE
sarra process going badly when the remote file could not be deleted.

### ISSUE THREAD

**Issue by habilinour** [MetPX/sarracenia#306] opened 2020-02-12 20:04 UTC
2020-02-12 16:41:03,449 [INFO] hb_memory cpu_times user=0.83 system=0.13 elapse=19614586.65
2020-02-12 16:41:03,449 [INFO] hb_memory current usage: 92.8 MiB, accumulating count (13 or 14 of 100 so far) before setting threshold
2020-02-12 16:41:03,449 [INFO] hb_pulse message_count 14 publish_count 13
2020-02-12 16:41:03,449 [INFO] hb_retry on_heartbeat
2020-02-12 16:41:03,449 [INFO] sr_retry on_heartbeat
2020-02-12 16:41:03,451 [INFO] No retry in list
2020-02-12 16:41:03,451 [INFO] sr_retry on_heartbeat elapse 0.001548
2020-02-12 16:41:45,418 [ERROR] unable to delete remote file OB.ON.AMEC.RONNW10.20200212163800.cmml
2020-02-12 16:41:45,419 [WARNING] plugin modified parent.msg.time works for now, but should replace with parent.msg.pubtime
2020-02-12 16:41:45,419 [INFO] file_log downloaded to: /apps/sarra/public_data/20200212/AMEC/RWIN/CMML/16/OB.ON.AMEC.RONNW10.20200212163800.cmml_d,2510ec10126a2615a8b99038bd007d55
2020-02-12 16:41:45,419 [INFO] post_log notice=20200212164145.419066668 http://host/20200212/AMEC/RWIN/CMML/16/OB.ON.AMEC.RONNW10.20200212163800.cmml_d,2510ec10126a2615a8b99038bd007d55 headers={'to_clusters': 'DDSR.CMC,DDI.CMC,CMC,SCIENCE,EDM', 'parts': '1,7439,1,0,0', 'sum': 'd,2510ec10126a2615a8b99038bd007d55', 'sundew_extension': 'PULL:MTO:AMEC:3:CMML:20200212164106', 'source': 'AMEC', 'from_cluster': 'DDSR.CMC'}
**2020-02-12 16:42:05,408 [ERROR] sr_sarra/run going badly with signal alarm timed out, sleeping for 0.010.
2020-02-12 16:44:53,003 [ERROR] unable to delete remote file** OB.ON.AMEC.RONNR14.20200212164000.cmml
2020-02-12 16:44:53,004 [WARNING] plugin modified parent.msg.time works for now, but should replace with parent.msg.pubtime

**Comment by petersilva** [comment] 2020-02-13 13:02
the *unable to delete* is two minutes after the *going badly* message, and the file name is different. I do not think the two messages are related.   We have no idea why it is failing.  The *going badly* thing is this awful catch-all around 'process_message', so the root cause could be anything.
The next source line after that is a stack trace that prints only in debug mode.   I'm thinking about making that an error message so every time going badly happens we will get a stack trace.   Does this happen often? Can you turn on debug for a short period to get more detail of this problem?

**Comment by petersilva** [comment] 2020-02-13 13:04
I know analysts don't like seeing stack traces, but I think this particular place, where the try/except is surrounding hundreds of lines of code in many different files, printing a stack trace all the time makes more sense than forcing people to turn on debug.  What do you think?

**Comment by petersilva** [comment] 2020-02-13 13:08
the plugin message is also interesting... does this config include custom plugins.

**Comment by habilinour** [comment] 2020-02-13 13:42
The stack traces are very helpful to track down the issues in  the code, but they scare the analysts when they show up in the logs as an error. The analysts might need to be familiar with the code and figure out it's not harmless.

**Comment by habilinour** [comment] 2020-02-13 13:55
Interesting. Here are the plugins the process uses. 
```
# plugin to make the products with unique names

on_file None
plugin  sumstr_ext
on_file file_log
```

**Comment by petersilva** [comment] 2020-02-14 11:49
stack trace: If we don't want stack traces normally, then one has to turn on debug to see them.  That is what the code currently does Can you do that for this case, for a short time to get a stack trace?

on plugins... The error message is saying that a plugin is playing with self.msg.time in a plugin...   
The file_log is included in the release has no reference to time.  You may remove ~/.config/sarra/plugins/file_log.py if it is present, or examine it and fix it. It is perhaps more likely that substr_ext modifies this value?  if not, then this might be a bug.

**Comment by petersilva** [comment] 2020-02-21 23:01
potential fix is: a71d5167a3c0d36ad54d6e5f10a31a17580bc79d

**Comment by petersilva** [comment] 2020-02-26 03:19
please confirm if this is fixed in 2.20.02b3

**Comment by habilinour** [comment] 2020-02-27 20:54
The issue seems to be fixed.

**Comment by petersilva** [comment] 2020-02-28 18:52
yeay!

**Closed by petersilva** 2020-02-28 18:52 UTC
Labels: bug, likely-fixed
