### ISSUE TITLE
sr3 show shows the wrong exchange

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#922] opened 2024-02-02 20:06 UTC
both post_exchange and (source) exchange are the same in sr3 show.

```
~/.config/sr3/sarra$ cat get_eumetsat.conf
broker   amqp://root@localhost/
exchange      xs_EUMETSAT

post_broker amqp://root@localhost/
post_exchange xpublic

source EUMETSAT

callback accept.auth_eumetsat

directory /tmp/eumetsat
accept .*
#reject .*

# poll posts v03 format messages
topicPrefix v03

set accept.auth_eumetsat.logLevel debug



~/.config/sr3/sarra$ sr3 show sarra/get_eumetsat | grep -i exchange
2024-02-02 20:05:41,925 2095683 [INFO] sarracenia.flow loadCallbacks flowCallback plugins to load: ['sarracenia.flowcb.post.message.Message', 'sarracenia.flowcb.gather.message.Message', 'sarracenia.flowcb.retry.Retry', 'sarracenia.flowcb.housekeeping.resources.Resources', 'accept.auth_eumetsat', 'log']
2024-02-02 20:05:41,975 2095683 [INFO] sarracenia.flowcb.log __init__ sarra initialized with: logEvents: {'after_post', 'after_accept', 'on_housekeeping', 'after_work'},  logMessageDump: False
 'declared_exchanges': [],
 'exchange': ['xpublic'],
 'exchangeDeclare': True,
 'post_exchange': ['xpublic'],
 'post_exchanges': [],
 'resolved_exchanges': ['xpublic'],
 'sourceFromExchange': False,
```

**Comment by petersilva** [comment] 2024-02-02 20:32
I copy/pasted your config, saw:

```

fractal% sr3 show sarra/get_eumetsat |& grep exchange
 'declared_exchanges': [],
 'exchange': 'xs_EUMETSAT',
 'exchangeDeclare': True,
 'post_exchange': 'xpublic',
 'post_exchanges': [],
fractal% 

```

weird...

**Comment by petersilva** [comment] 2024-02-03 03:35
It's confirmed it seems to be a display thing... perhaps at worst it might affect sr3 declare.
At any rate, the symptom is fixed by the patch above.

**Closed as completed** 2024-02-05 15:10 UTC
Labels: bug, likely-fixed, Priority 5  - Defect, v3only
