### ISSUE TITLE
Incorrect young files found with `fileAgeMin` get retried instead of rejected in a poll

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#1254] opened 2024-10-09 14:04 UTC
We have a poll in production that has a fast polling interval (scheduled_interval) and has `fileAgeMin` set to a value above the polling interval.

```
# For my use case, in the poll config
scheduled_interval 15
fileAgeMin 30

accept .*_124.QC2
acceptUnmatched False
```

Essentially this configuration means that all new files should get noticed by `fileAgeMin`.

With our current code, this means that the file will get appended to a `worklist.failed` list upon notice.

 https://github.com/MetPX/sarracenia/blob/91d8cca913a006e81ebb759a6590a7e5585dfefb/sarracenia/flow/__init__.py#L1011-L1014

I'm not sure but I think a message appended to `worklist.failed` will bypass the filtering and will get retried in the work phase of the code.

This means that **any** file that is too young and would usually get rejected, now will get retried. 
In our use case, for a poll, this means that the wrong files are getting posted.

For our operational use case, this is what was observed, which seems to confirm the above theory
The `SK1` file should normally get rejected, but doesn't and gets posted anyways
```
The 100904.SK1 gets noticed, but is too young!
	ddsr-cmc-ops10: 2024-10-09 10:15:26,367 [WARNING] sarracenia.flow filter file too young: queueing for retry.
	ddsr-cmc-ops10: 2024-10-09 10:15:26,370 [DEBUG] sarracenia.flow filter B filtered incoming: 0, ok: 0 (directories: 0), rejected: 66, failed: 1 stop_requested: False have_vip: 142.135.12.141

The message gets appended to the retry queue. 
	ddsr-cmc-ops10: 2024-10-09 10:15:26,370 [DEBUG] sarracenia.diskqueue put DEBUG add to new file diskqueue_work_retry_01.new {'_format': 'v02', '_deleteOnPost': {'new_relPath', 'new_file', '
	new_dir', 'post_format', 'mode', 'exchange', 'new_subtopic', 'subtopic', '_format', 'new_baseUrl', 'local_offset'}, 'exchange': ['xs_PROVINCIAL_mtl_depot'], 'local_offset': 0, 'pubTime': '
	20241009T101526.220653057', 'sundew_extension': 'AQ_EST:MTL:AIRNOW:AQCSV:', 'new_dir': '/data/depot/ftpusers/airnow2', 'new_file': '100904.SK1', 'post_format': 'v02', 'new_baseUrl': 'ftp:/
	/pds@accessdepot3.cmc.ec.gc.ca/', 'new_relPath': 'data/depot/ftpusers/airnow2/100904.SK1', 'new_subtopic': ['data', 'depot', 'ftpusers', 'airnow2'], 'relPath': 'data/depot/ftpusers/airnow2
	/100904.SK1', 'subtopic': ['data', 'depot', 'ftpusers', 'airnow2'], 'baseUrl': 'ftp://pds@accessdepot3.cmc.ec.gc.ca/', 'from_cluster': 'DDSR.CMC', 'source': 'PROVINCIAL', 'identity': {'met
	hod': 'cod', 'value': 'sha512'}, 'mode': '660', 'size': 5131, 'mtime': '20241009T101500'}

After a while, housekeeping runs and the retries get retried
	ddsr-cmc-ops10: 2024-10-09 10:20:09,549 [DEBUG] sarracenia.diskqueue msg_get_from_file DEBUG /local/home/sarra/.cache/sr3/poll/airnow_mtl_depot3/diskqueue_work_retry_01 open read
	ddsr-cmc-ops10: 2024-10-09 10:20:09,551 [DEBUG] sarracenia.flowcb.nodupe.disk check_message NoDupe calling check( data/depot/ftpusers/airnow2/100904.SK1,20241009T101500,5131, data/depot/ft
	pusers/airnow2/100904.SK1 )
	ddsr-cmc-ops10: 2024-10-09 10:20:09,551 [DEBUG] sarracenia.flowcb.nodupe.disk _not_in_cache adding entry to NoDupe cache
	ddsr-cmc-ops10: 2024-10-09 10:20:09,551 [DEBUG] sarracenia.flowcb.nodupe.disk after_accept items registered in duplicate suppression cache: 463
	ddsr-cmc-ops10: 2024-10-09 10:20:09,551 [INFO] sarracenia.flowcb.log after_accept accepted: (lag: 283.33 ) ftp://pds@accessdepot3.cmc.ec.gc.ca/ /data/depot/ftpusers/airnow2/100904.SK1
	ddsr-cmc-ops10: 2024-10-09 10:20:09,551 [DEBUG] sarracenia.flow filter B filtered incoming: 1, ok: 0 (directories: 0), rejected: 67, failed: 0 stop_requested: False have_vip: 142.135.12.14
	1
	ddsr-cmc-ops10: 2024-10-09 10:20:09,551 [DEBUG] sarracenia.flow do processing 1 messages worked!
	ddsr-cmc-ops10: 2024-10-09 10:20:09,552 [DEBUG] sarracenia.flowcb.retry after_work loading from post_retry_001: qty=11 ... got: 0
	ddsr-cmc-ops10: 2024-10-09 10:20:09,554 [INFO] sarracenia.flowcb.log after_post posted to exchange: xs_PROVINCIAL_mtl_depot topic: v02.post.data.depot.ftpusers.airnow2 a file with baseUrl: ftp://pds@accessdepot3.cmc.ec.gc.ca/ relPath: data/depot/ftpusers/airnow2/100904.SK1
```

## Work around
- Add `retry_refilter True` in the poll configuration

**Comment by reidsunderland** [comment] 2024-10-09 14:13
`retry_refilter True` might be a workaround?

**Comment by petersilva** [comment] 2024-10-09 14:40
OK... so discussing with @andreleblanc11 it seems like what we really need is a separate retry queue for stuff that hasn't been filtered yet... having a separate retry queue is probably better than just global retry_refilter?

So we would have a third retry (in addition to download_retry and post_retry, have gather_retry? or filter_retry? ) and the early rejections (like fileAgeMin) go there.

This is only needed if the retry_refilter option causes problems where some files need to be refiltered and others not.  We probably want to confirm that is the case before going to the trouble of implementing another retry_queue.

**Comment by petersilva** [comment] 2024-10-09 14:43
* If we don't implement a separate filter/gather retry queue, then we likely need a note on the *fileAgeMin* option to say one must specify *retry_refilter on* when using that option.
* and/or we could set default on *poll/scheduled flow* anything that doesn't download? component to have *retry_refilter on* ?

This is a case of *Works As Designed*... meaning the subtly bad behaviour will always be *available* unless we implement an additional retry queue.

**Comment by andreleblanc11** [comment] 2024-10-09 15:50
Adding `retry_refilter True` to the poll correctly rejected the file when it got refiltered

**Comment by petersilva** [comment] 2024-10-21 14:58
* discussed changing default of *retry_refilter* for polls/shovels/winnow/watches.
  * would almost always want this on... likely a good default...
  * downside of different defaults for different components is people forget what defaults are for all configs and put settings in everywhere (stop relying on defaults, defeating the purpose.)

* discussed "fileAgeMin" error message unless *retry_refilter* is true AND retry is active (retry_ttl > 0) ... 

Probably BOTH is a good thing to do... since the former is likely easier to work with, and the latter will catch explicit but subtle mis-configurations.

* Could also change default for retry_refilter to True for all by default...
  * use cases... in sender, directory was wrong, in v2, stop/start... would send to the right place.
  * accept renamers... need to be re-entrant... have had cases where files get double (or N) suffixes because renamers always add. 
  
more baking?

**Comment by reidsunderland** [comment] 2024-11-28 14:57
It would be good to try to figure out a fix for this in the next release

**Comment by petersilva** [comment] 2024-12-02 16:12
so... issue is... this code:

https://github.com/MetPX/sarracenia/blob/a4af0e2c21f211e1d993c3a183b8eed63dbfb09c/sarracenia/flow/__init__.py#L1012-L1015

is "wrong" in a poll... but it's ok in other circumstances.  Is it as easy as doing something different in a poll component versus other s?  or do we need something more elaborate...

folks seem to think if self.o.component != 'poll'  would be enough?

**Closed as completed** 2024-12-11 18:17 UTC
Labels: bug, work-around, Priority 3 - Important, v3
