### ISSUE TITLE
sr3 delete config option deleting destination files rather than source

### ISSUE THREAD

**Issue by tysonkaufmann** [MetPX/sarracenia#605] opened 2022-12-28 17:05 UTC
In testing we (@reidsunderland & @andreleblanc11) found that including the delete option on a sarra config and well as a subscriber config results in the deletion of the downloaded file rather than the desired v2 functionality of deleting the source file. 

Sample configs to reproduce the issue:

### test-watch.conf
```
post_broker amqp://feeder@localhost/
post_exchange xpublic

post_baseUrl file:/

path /users/dor/aspy/anl/sarra-test/input/

logLevel debug

fileEvents modify,create
```

### test-subscribe.conf
```
broker amqp://feeder@localhost/
exchange xpublic

delete True
#discard True

directory /users/dor/aspy/anl/sarra-test/output/
accept .*

logLevel debug
```

We altered the code below and replaced the `remote_file` with `'/' +msg['relPath']` for testing, and that change resulted in the file being deleted at the source, but also being deleted at the destination.

Applicable code: https://github.com/MetPX/sarracenia/blob/main/sarracenia/flow/__init__.py#L1644-L1661

Here is the sample of the log file for the subscriber after we made the above change to the `remote_file`:
```
2022-12-28 16:27:15,242 [INFO] sarracenia.flowcb.log after_accept accepted: (lag: 3.85 ) file:/ users/dor/aspy/anl/sarra-test/input/testfile6_delete.txt
2022-12-28 16:27:15,243 [DEBUG] sarracenia.flow download file_transport download relPath=users/dor/aspy/anl/sarra-test/input/testfile6_delete.txt
2022-12-28 16:27:15,244 [DEBUG] sarracenia.flow download Beginning fetch of file://users/dor/aspy/anl/sarra-test/input/testfile6_delete.txt  into testfile6_delete.txt 0--1
2022-12-28 16:27:15,244 [DEBUG] sarracenia.flow download hasAccel=True, thresh=0, len=0, remote_off=0, local_off=0 inflight=testfile6_delete.txt
2022-12-28 16:27:15,248 [DEBUG] sarracenia.transfer.file delete sr_file rm /users/dor/aspy/anl/sarra-test/input/testfile6_delete.txt
2022-12-28 16:27:15,248 [DEBUG] sarracenia.flow download file deleted on remote site users/dor/aspy/anl/sarra-test/input/testfile6_delete.txt
2022-12-28 16:27:15,248 [DEBUG] sarracenia.flow do_download downloaded ok: /users/dor/aspy/anl/sarra-test/output/testfile6_delete.txt
2022-12-28 16:27:15,249 [INFO] sarracenia.flowcb.log after_work downloaded ok: /users/dor/aspy/anl/sarra-test/output/testfile6_delete.txt
2022-12-28 16:27:17,255 [INFO] sarracenia.flowcb.log after_accept accepted: (lag: 0.86 ) file:/ users/dor/aspy/anl/sarra-test/input/testfile6_delete.txt
2022-12-28 16:27:17,255 [DEBUG] sarracenia.flow removeOneFile path to remove: /users/dor/aspy/anl/sarra-test/output/testfile6_delete.txt
2022-12-28 16:27:17,256 [INFO] sarracenia.flow removeOneFile removed /users/dor/aspy/anl/sarra-test/output/testfile6_delete.txt
2022-12-28 16:27:17,256 [INFO] sarracenia.flowcb.log after_work removed ok: /users/dor/aspy/anl/sarra-test/output/testfile6_delete.txt
```

It is relevant to note that the `removeOneFile` function is the one deleting the file from the `.../output/` directory.

**Comment by reidsunderland** [comment] 2022-12-28 18:00
We did more testing, `removeOneFile` seems to be working as expected. The initial bug is that `delete True` for subscribers was not working correctly. Once that was fixed, files were being deleted from the source (correct) and causing the watch to send another message with `fileOp: {'remove':''}`, causing the subscriber to delete the file.

1. Tyson touches testfile.txt to create the file
2. Watch notices and posts testfile.txt being created
3. Subscriber downloads testfile.txt
4. Subscriber deletes testfile.txt
5. Watch notices that testfile.txt is deleted, posts another message with `fileOp: {'remove':''}` (incorrect behavior)
6. Subscribe receives the fileOp remove message and deletes the file it downloaded before.

In another test, we set `delete False` in the subscriber config, and the incorrect behavior still happens:

1. Tyson touches testfile.txt to create the file
2. Watch notices and posts testfile.txt being created
3. Subscriber downloads testfile.txt
4. Tyson manually deletes the input testfile.txt with `rm input/testfile.txt`
5. Watch notices that testfile.txt is deleted, posts another message with `fileOp: {'remove':''}` (incorrect behavior)
6. Subscribe receives the fileOp remove message and deletes the file it downloaded before.

Tyson's watch config had `fileEvents modify,create` and we also tried with only `fileEvents create`, but watch seems to be ignoring the `fileEvents` in Tyson's config file. The log shows that it's using the default `fileEvents` settings `'fileEvents': {'link', 'modify', 'delete', 'create'},`.

There is at least one bug, `delete True` doesn't delete source files correctly. I think it needs to delete the full file path instead of just trying to delete `remote_file` (which is only the file name).

https://github.com/MetPX/sarracenia/blob/3a9217497937b462b55bae1da594f7d4b54e59d7/sarracenia/flow/__init__.py#L1644-L1661

But there might be a watch/config parsing bug for fileEvents as well?

**Comment by petersilva** [comment] 2022-12-28 18:36
I'm not sure, but I think remote_file used to be ok, because I think the transfer protocol class (and corresponding v2 code), if you look at it, always writes files to cwd.  it does a chdir before any get or put... but that might be a bug... in v2... files were processed one at a time, so the cwd would have been the same as when the fetch was done and the later delete... with sr3 working with batches, the cwd can now be different... hmm...  might have to add a chdir before every delete... not sure... it depends on when the delete happens.. if it is in the same loop right after the download, then it is probably still fine. if it is in a later step (after_work or something) then it's probably currently wrong.

**Comment by petersilva** [comment] 2022-12-28 18:46
I'm wondering about clarity of the options.  Would it be helpful to rename the *delete* and *discard* options for sr3:

*deleteUp* or *deleteSource*   vs.  "deleteDown* or *deleteDestination* 

or some other name that identifies what the settings do more obviously.

**Comment by tysonkaufmann** [comment] 2022-12-28 21:54
I think renaming `delete` and `discard` to be more intuitive is a good idea. At face value they sound interchangeable.

I would cast my vote for `deleteSource` and `deleteDestination`, unless there are any other recommendations

Or - would it be easier to have three options for delete rather than two config directives? ie. `delete source` `delete destination` `delete all` ?

**Comment by reidsunderland** [comment] 2022-12-28 22:27
The delete (from source) works fine using sftp, so transfer/file.py seems to be the source of the bug. `os.chdir` is commented out 😄 

https://github.com/MetPX/sarracenia/blob/e7d7af2b89d9a6cf03bcdcaabcce27ae776a17e4/sarracenia/transfer/file.py#L70-L80

Uncommenting it seems to work properly. But I'm having an issue with files being double posted by my watch when I `touch` them...

---

I think deleteSource and deleteDestination would be good names. I also like Tyson's suggestion of `delete source` `delete destination` `delete all`. Is discard implemented? 

---

The code for sets in config.py might be wrong - it's doing a set union (|) of the default fileEvents (create, delete, modify and link) which is causing fileEvents to *always* be all of the defaults.  @petersilva should this be `&` (intersection)? 

```python
            if hasattr(self, option):
                sv= getattr(self,option) | sv
```

**Comment by petersilva** [comment] 2022-12-28 23:51
on the option discusison... would delete then become a list/set option?

*delete source*
*delete destination*
*delete source,destination*

leaves room for later (could add other keywords...) I dunno if I like all.. I think we will just have to document that all means source,destination ... which seems redundant.

on @reidsunderland's questions about fileEvents... 

* 1st clarification:   the *delete* in file events has nothing to do with the *delete* option... the fileEvent one is about noticing when files are deleted in either the shim library, or a directory watch, and generating posts for those.

that out of the way...  how to parse fileEvent options is an interesting question.  I think to suppress defaults, one can do:

*fileEvents None*   <-- sets to empty set
*fileEvents create*  <-- add create
*fileEvents modify,delete*  <--add modify and delete

and you should end up with fileEvents list being to set(create,delete,modify) so that way the OR operation makes sense.  It is easy to see why we would want to make each setting override all previous ones, in which case, it would just be set(vs) ... not sure what makes the most sense.

**Comment by petersilva** [comment] 2022-12-29 00:48
for the double posting on touch... I think that is because there are two events generated... I am currently struggling with the same problem on the C side... if you do an strace... you see:

**strace touch kk** ...

```
.
.
.
openat(AT_FDCWD, "kk", O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = 3
dup2(3, 0)                              = 0
close(3)                                = 0
utimensat(0, NULL, NULL, 0)             = 0
close(0)                                = 0
close(1)                                = 0
close(2)                                = 0
exit_group(0)  

```

there is an open returning file descriptor == 3, then a dup making fd 0 a second opening of fd 3,
and then a close of fd 3, followed by a close of fd  0... so the open of "kk" happens once, but the file
is closed twice.  the closing a writable file is what creates an event.

**Comment by petersilva** [comment] 2023-01-06 18:45
working on other stuff (building CI/CD for metpx-sr3c), I found a bug in the transfer/file.py that wasn't interpreting cwd at source during a download.  fixed here:

099c043286943c131cca0a100d3d7ed09570b959

this might fix what is the root problem here?  You can try pulling v03_wip, and see if it behaves better.

**Comment by petersilva** [comment] 2023-01-06 20:41
I have fixed the issue with double posting for duped files (like with *touch*) on the C shim library side by recording files *duped* and then not publishing when the first fd is closed... but I don't think that approach will work for *watch*  (or cpost) as *dup* is just a system call, it doesn't cause any file event to be noticed by inotify...

**Comment by petersilva** [comment] 2023-01-11 18:37
changes are in v3.00.25... available for testing.

**Comment by reidsunderland** [comment] 2023-01-12 18:20
When I tested the delete still wasn't working. I might have done something wrong... but we're thinking that we need to change the delete method (or calls to delete) to include `self.cwd` instead of just the filename. 

fileEvents is working as designed, but we might discuss changing it.

**Closed** 2023-01-27 15:38 UTC
Labels: bug, Priority 2 - Critical, v3
