### ISSUE TITLE
port remaining v2 plugins to v03

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#400] opened 2021-08-24 21:21 UTC
* port rest of v02 plugins to v03 equivalents and add mappings in config.py,
  so that we have barely any v2's left.

look at the plugins directory, and gradually empty it out in favour of flowcb.

**Comment by MagikEh** [comment] 2022-05-02 18:33
Duplicate of #433

**Closed by MagikEh** 2022-05-02 18:33 UTC
Labels: Design, Developer, v3only
