### ISSUE TITLE
Error on Exit on v3.0.44

### ISSUE THREAD

**Issue by gc-nrcan-michael** [MetPX/sarracenia#770] opened 2023-10-11 22:34 UTC
Follow up to issue #753.

With Sarracenia 3.0.44, the following Dockerfile works, without python-magic:

```.Dockerfile
FROM ubuntu:latest


RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY ./app .

RUN pip3 install -r requirements.txt

RUN pip install metpx-sr3
RUN pip3 install metpx-sr3[amqp,mqtt,vip]
RUN pip3 install metpx-sr3


EXPOSE 5671
EXPOSE 5672
EXPOSE 15671
EXPOSE 15672


CMD [ "python3", "./__main__.py" ]

```

Although on exit, there is a new error:

```
********************************************************************************
Docker App ECCC-to-Cloud: Running
********************************************************************************
Sarracenia AMQP URL: "amqps://anonymous:anonymous@hpfx.collab.science.gc.ca"
Sarracenia topic prefix: "v02.post"
Sarracenia binding: "#"
Sarracenia queue name tag: "LOCAL_TEST"
Send One Message Then Quit mode: True
Mock Sarracenia and only receive test data: True
Mock Event Grid send: True
process: iteration 
count = 0, totalMessageCount = 0
listen_for_messages: returning MOCK Sarracenia data
send_message_batch: send_one_message_then_quit is True, truncating message batch
mock_event_grid_send is True, not sending events
events that would have been sent:
event 0:
CloudEvent(source=docker:eccc_to_cloud:amqps://anonymous:anonymous@hpfx.collab.science.gc.ca/v02.post/#, type=eccc-v1, specversion=1.0, id=3b8d1571-fb1e-4620-a577-b2c7d87aff75, time=2023-10-11 22:36:52.236370+00:00)
event.data =       
{'url': 'https://hpfx.collab.science.gc.ca//20230425/WXO-DD/observations/swob-ml/20230425/CNPL/2023-04-25-2100-CNPL-AUTO-swob.xml', 'group': 'SWOBAUTO'}
send_one_message_then_quit is True, exiting    
sarracenia.moth.amqp:deleteing queue q_anonymous_8dea9a90d820_NRCAN_LOCAL_TEST
ERROR:sarracenia.moth.amqp:failed to hpfx.collab.science.gc.ca with 'AMQP' object has no attribute 'channel'
InfiniteLoopProcess: exit_gracefully - exiting gracefully

********************************************************************************
Docker App ECCC-to-Cloud: process complete
********************************************************************************
```

Specifically:

```
ERROR:sarracenia.moth.amqp:failed to hpfx.collab.science.gc.ca with 'AMQP' object has no attribute 'channel'
```

This probably is a non-breaking issue although I'm noting this because it's still a new error.

**Comment by petersilva** [comment] 2023-10-13 21:59
as an aside... I don't know the reason for "send_one_message_then_quit" but you can do the same thing with the setting:  

```
messageCountMax 1
```
or in python
```
options.messageCountMax = 1

```

**Comment by petersilva** [comment] 2023-10-14 00:39
so... trying a few things, I don't see this behaviour here. I made a wild stab at it you can try out this branch and see if it helps:

```

     git clone --branch 770-error-on-exit-on-v3044  https://github.com/MetPX/sarracenia sr3
     cd sr3
     pip install .

```

If you can install it that way in your container to test, and see if you have the same error.
if not, maybe it is fixed.

**Comment by petersilva** [comment] 2023-10-19 06:14
@gc-nrcan-michael if you can let us know if you can test it, that would be great.
I haven't been easily able to reproduce it, so not sure the fix is good.

**Comment by gc-nrcan-michael** [comment] 2023-10-19 18:40
Hi Peter, just saw this message.

Currently in the process of upgrading infrastructure setup, I will test this asap.

**Comment by gc-nrcan-michael** [comment] 2023-10-24 21:22
Okay, I just tested the update with the following Dockerfile:

```.Dockerfile
FROM ubuntu:latest


RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    && rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN git clone --branch 770-error-on-exit-on-v3044  https://github.com/MetPX/sarracenia sr3
WORKDIR /sr3
RUN pip3 install .


WORKDIR /app

COPY ./app .

RUN pip3 install -r requirements.txt

RUN pip install metpx-sr3
RUN pip3 install metpx-sr3[amqp,mqtt,vip]
RUN pip3 install metpx-sr3


EXPOSE 5671
EXPOSE 5672
EXPOSE 15671
EXPOSE 15672


CMD [ "python3", "./__main__.py" ]
```

and the following output is produced:

```
INFO:root:********************************************************************************
INFO:root:Docker App ECCC-to-Cloud: Running
INFO:root:********************************************************************************
INFO:root:Sarracenia AMQP URL: "amqps://anonymous:anonymous@hpfx.collab.science.gc.ca"
INFO:root:Sarracenia topic prefix: "v02.post"
INFO:root:Sarracenia binding: "#"
INFO:root:Sarracenia queue name tag: "LOCAL_TEST"
INFO:root:Send One Message Then Quit mode: True
INFO:root:Mock Sarracenia and only receive test data: True
INFO:root:Mock Event Grid send: True
INFO:root:process: iteration count = 0, totalMessageCount = 0
INFO:root:listen_for_messages: returning MOCK Sarracenia data
INFO:root:send_message_batch: send_one_message_then_quit is True, truncating message batch
INFO:root:Running send_message_batch, sending 1 messages
INFO:root:mock_event_grid_send is True, not sending events
INFO:root:events that would have been sent:
INFO:root:event 0:
INFO:root:CloudEvent(source=docker:eccc_to_cloud:amqps://anonymous:anonymous@hpfx.collab.science.gc.ca/v02.post/#, type=eccc-v1, specversion=1.0, id=e8a7d568-d65c-4c43-bfd8-3939692c75a0, time=2023-10-24 21:17:13.126701+00:00)
INFO:root:event.data =
INFO:root:{'url': 'https://hpfx.collab.science.gc.ca//20230425/WXO-DD/observations/swob-ml/20230425/CNPL/2023-04-25-2100-CNPL-AUTO-swob.xml', 'group': 'SWOBAUTO'}
INFO:root:send_one_message_then_quit is True, exiting
INFO:sarracenia.moth.amqp:deleting queue q_anonymous_2b47c4c236b5_NRCAN_LOCAL_TEST
InfiniteLoopProcess: exit_gracefully - exiting gracefully
********************************************************************************
Docker App ECCC-to-Cloud: process complete
********************************************************************************
```

This version of Sarracenia works and does not produce the error in question.

**Comment by petersilva** [comment] 2023-10-24 21:34
OK Great! we just missed 3.0.45 ... it will get merged in the next version.  Thanks for testing that!

**Closed** 2023-11-06 16:55 UTC
Labels: bug, help wanted, harmless, v3, v3only
