### ISSUE TITLE
ImportError within virtualenv setup

### ISSUE THREAD

**Issue by tomkralidis** [MetPX/sarracenia#214] opened 2019-06-05 13:25 UTC
Using a virtualenv results in `ImportError`s against locally installed packages.  Sample setup in https://gist.github.com/tomkralidis/cf42f051f1a109034a3800daaf51beb5

Invoking `sr_subscribe bulletins.conf foreground` results in:
```
2019-06-05 13:21:50,562 [INFO] confirmed added to the retry process 20190605131948.546 http://dd4.weather.gc.ca /bulletins/alphanumeric/20190605/SR/KWAL/13/SRCN40_KWAL_051319___79396
2019-06-05 13:21:50,562 [ERROR] sr_subscribe/run going badly, so sleeping for 5.12 Type: <class 'ImportError'>, Value: No module named 'elasticsearch',  ...
```

How can one ensure packages installed within a virtualenv setup are imported properly?

**Comment by petersilva** [comment] 2019-06-05 20:30
first thing: 

You wrote pip... on every linux I have seen, I need to write pip3.  Are you using python2 or python3?

second thing, you can install sarra within the same environment, might have better luck:

`pip3 install metpx-sarracenia
`

**Comment by tomkralidis** [comment] 2019-06-05 20:37
> You wrote pip... on every linux I have seen, I need to write pip3. Are you using python2 or python3?

Python 3.  Once you init a virtualenv via Python 3, pip is Python 3 anyway (same as pip3).

> second thing, you can install sarra within the same environment, might have better luck:
> pip3 install metpx-sarracenia 

No dice:
```bash
$ pip install metpx-sarracenia
Downloading/unpacking metpx-sarracenia
  Could not find a version that satisfies the requirement metpx-sarracenia (from versions: 2.15.12a1, 2.15.12a2, 2.15.12a3, 2.15.12a4, 2.16.01a1, 2.16.01a2, 2.16.01a3, 2.16.01a4, 2.16.01a5, 2.16.01a6, 2.16.01a7, 2.16.01a8, 2.16.02a1, 2.16.02a2, 2.16.02a3, 2.16.02a4, 2.16.03a1, 2.16.03a2, 2.16.03a3, 2.16.03a4, 2.16.03a5, 2.16.03a6, 2.16.03a7, 2.16.03a8, 2.16.03a9, 2.16.03a10, 2.16.05a1, 2.16.05a2, 2.16.07a1, 2.16.07a2, 2.16.07a3, 2.16.08a1, 2.16.10a1, 2.16.10a2, 2.16.11a1, 2.16.11a2, 2.16.11a3, 2.16.11a4, 2.17.2a1, 2.17.3a2, 2.17.3a3, 2.17.3a4, 2.17.3a5, 2.17.6a1, 2.17.6a2, 2.17.6a3, 2.17.7a1, 2.17.7a2, 2.17.7a3, 2.17.7a4, 2.17.8a1, 2.17.9a1, 2.17.10a1, 2.17.10a2, 2.17.10a3, 2.17.10a4, 2.17.11a1, 2.17.11a2, 2.17.11a3, 2.17.12a1, 2.17.12a2, 2.17.12a3, 2.17.12a4, 2.17.12a5, 2.17.12a6, 2.17.12a7, 2.17.12a8, 2.18.1a1, 2.18.1a2, 2.18.1a3, 2.18.1a4, 2.18.1a5, 2.18.2a1, 2.18.3a2, 2.18.3b1, 2.18.4b2, 2.18.4b3, 2.18.4b4, 2.18.4b5, 2.18.5b1, 2.18.5b2, 2.18.5b4, 2.18.6b2, 2.18.7b1, 2.18.7b2, 2.18.7b3, 2.18.8b1, 2.18.9b1, 2.18.9b2, 2.18.10b1, 2.18.10b2, 2.18.11b1, 2.18.11b2, 2.18.11b3, 2.18.11b4, 2.18.11b5, 2.18.11b6, 2.18.12b4, 2.19.1b1, 2.19.2b1, 2.19.2b2, 2.19.2b3, 2.19.3b1, 2.19.3b2, 2.19.3b3, 2.19.3b4, 2.19.3b5, 2.19.3b6, 2.19.4b1, 2.19.4b2)
Cleaning up...
No distributions matching the version for metpx-sarracenia
Storing debug log for failure in /tmp/pip.log

$ pip3 install metpx-sarracenia
Downloading/unpacking metpx-sarracenia
  Could not find a version that satisfies the requirement metpx-sarracenia (from versions: 2.15.12a1, 2.15.12a2, 2.15.12a3, 2.15.12a4, 2.16.01a1, 2.16.01a2, 2.16.01a3, 2.16.01a4, 2.16.01a5, 2.16.01a6, 2.16.01a7, 2.16.01a8, 2.16.02a1, 2.16.02a2, 2.16.02a3, 2.16.02a4, 2.16.03a1, 2.16.03a2, 2.16.03a3, 2.16.03a4, 2.16.03a5, 2.16.03a6, 2.16.03a7, 2.16.03a8, 2.16.03a9, 2.16.03a10, 2.16.05a1, 2.16.05a2, 2.16.07a1, 2.16.07a2, 2.16.07a3, 2.16.08a1, 2.16.10a1, 2.16.10a2, 2.16.11a1, 2.16.11a2, 2.16.11a3, 2.16.11a4, 2.17.2a1, 2.17.3a2, 2.17.3a3, 2.17.3a4, 2.17.3a5, 2.17.6a1, 2.17.6a2, 2.17.6a3, 2.17.7a1, 2.17.7a2, 2.17.7a3, 2.17.7a4, 2.17.8a1, 2.17.9a1, 2.17.10a1, 2.17.10a2, 2.17.10a3, 2.17.10a4, 2.17.11a1, 2.17.11a2, 2.17.11a3, 2.17.12a1, 2.17.12a2, 2.17.12a3, 2.17.12a4, 2.17.12a5, 2.17.12a6, 2.17.12a7, 2.17.12a8, 2.18.1a1, 2.18.1a2, 2.18.1a3, 2.18.1a4, 2.18.1a5, 2.18.2a1, 2.18.3a2, 2.18.3b1, 2.18.4b2, 2.18.4b3, 2.18.4b4, 2.18.4b5, 2.18.5b1, 2.18.5b2, 2.18.5b4, 2.18.6b2, 2.18.7b1, 2.18.7b2, 2.18.7b3, 2.18.8b1, 2.18.9b1, 2.18.9b2, 2.18.10b1, 2.18.10b2, 2.18.11b1, 2.18.11b2, 2.18.11b3, 2.18.11b4, 2.18.11b5, 2.18.11b6, 2.18.12b4, 2.19.1b1, 2.19.2b1, 2.19.2b2, 2.19.2b3, 2.19.3b1, 2.19.3b2, 2.19.3b3, 2.19.3b4, 2.19.3b5, 2.19.3b6, 2.19.4b1, 2.19.4b2)
Cleaning up...
No distributions matching the version for metpx-sarracenia
Storing debug log for failure in /tmp/pip.log
```

**Comment by petersilva** [comment] 2019-06-05 20:41
That's odd, works fine in my environment ( no virtual env, just a default python3 on 18.04)

```
blacklab% pip3 install metpx-sarracenia
Collecting metpx-sarracenia
  Downloading https://files.pythonhosted.org/packages/7d/d9/d6c80fe88c2f374a98496f24bae4477662e2fd06e2c1d3faa005524e6211/metpx_sarracenia-2.19.4b2-py3-none-any.whl (374kB)
    100% |████████████████████████████████| 378kB 3.4MB/s 
Collecting watchdog (from metpx-sarracenia)
Collecting psutil (from metpx-sarracenia)
  Downloading https://files.pythonhosted.org/packages/c6/c1/beed5e4eaa1345901b595048fab1c85aee647ea0fc02d9e8bf9aceb81078/psutil-5.6.2.tar.gz (432kB)
    100% |████████████████████████████████| 440kB 3.2MB/s 
Collecting amqp (from metpx-sarracenia)
  Downloading https://files.pythonhosted.org/packages/45/91/877ea2d1c3234dbb32e818d281615232468ff8a4a783a8fc264862b9f77b/amqp-2.5.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 8.0MB/s 
Collecting appdirs (from metpx-sarracenia)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting humanize (from metpx-sarracenia)
Collecting netifaces (from metpx-sarracenia)
  Downloading https://files.pythonhosted.org/packages/0c/9b/c4c7eb09189548d45939a3d3a6b3d53979c67d124459b27a094c365c347f/netifaces-0.10.9-cp36-cp36m-manylinux1_x86_64.whl
Collecting argh>=0.24.1 (from watchdog->metpx-sarracenia)
  Using cached https://files.pythonhosted.org/packages/06/1c/e667a7126f0b84aaa1c56844337bf0ac12445d1beb9c8a6199a7314944bf/argh-0.26.2-py2.py3-none-any.whl
Collecting PyYAML>=3.10 (from watchdog->metpx-sarracenia)
  Downloading https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz (274kB)
    100% |████████████████████████████████| 276kB 3.2MB/s 
Collecting pathtools>=0.1.1 (from watchdog->metpx-sarracenia)
Collecting vine<5.0.0a1,>=1.1.3 (from amqp->metpx-sarracenia)
  Using cached https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl
Building wheels for collected packages: psutil, PyYAML
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /home/peter/.cache/pip/wheels/17/08/ec/22b464874958c3fc91e1a75748fae2220eb704a8b1035f9a03
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /home/peter/.cache/pip/wheels/ad/56/bc/1522f864feb2a358ea6f1a92b4798d69ac783a28e80567a18b
Successfully built psutil PyYAML
Installing collected packages: argh, PyYAML, pathtools, watchdog, psutil, vine, amqp, appdirs, humanize, netifaces, metpx-sarracenia
Successfully installed PyYAML-5.1 amqp-2.5.0 appdirs-1.4.3 argh-0.26.2 humanize-0.5.1 metpx-sarracenia-2.19.4b2 netifaces-0.10.9 pathtools-0.1.2 psutil-5.6.2 vine-1.3.0 watchdog-0.9.0
blacklab% 

```
I guess you can try... 
`
pip install metpx-sarracenia==2.19.4b2
`

**Comment by tomkralidis** [comment] 2019-06-05 20:49
This works, assuming one installs metpx-sarracenia in the same virtualenv.  We need to install via virtualenv for development given we don't have root access in our environments :)

**Comment by petersilva** [comment] 2019-06-05 22:29
I'm not saying it's ideal.  I'm saying python environments are are a maze of corridors all different.  basically the application works with the python environment it has... I imagine another way of doing things would be to set PYTHONPATH to include the system ones, and venv ones... or is that what venv does?

**Comment by petersilva** [comment] 2019-06-05 23:19
for bonus points: repeat in anaconda.

**Comment by tomkralidis** [comment] 2019-06-06 00:50
To add, when importing packages, is there any reason why imports do not work outside the given function corresponding to `on_file`, `on_message` etc. binding?  For example, the setup in https://gist.github.com/tomkralidis/cf42f051f1a109034a3800daaf51beb5#file-bulletin_es_loader-py-L69 works, but if I try to move the import outside the class (like to the top of the file) or even outside of the specific function, I get errors (i.e. as if the module was never imported).

**Comment by petersilva** [comment] 2019-06-06 00:59
not saying this is a good thing, but it is what is observed: The file is exec'd/interpreted in one context, and then the entry points assigned.   The routine is then invoked in another context using that assignment, where the imports that are in place from the file doing the call... it's definitely a quirk,  not clear what to do about it.

**Comment by tomkralidis** [comment] 2019-06-06 01:16
This is where importing the file via `importlib` may be helpful (related discussion in #213).

**Comment by petersilva** [comment] 2019-06-06 02:29
This would need to be a project.  I don't understand why importlib would make any difference... but I don't know that it doesn't.

**Comment by benlapETS** [comment] 2019-06-06 20:16
I agree on that, we would need a real plugin framework that would be more OO, but it is not easy to port without breaking stuff for now. Like Peter said it would be a project on its own...

**Comment by petersilva** [comment] 2019-06-08 05:30
The complaint is a description of how the current import system works... It does work that way, and it does suck, but this isn´t a bug that can be fixed.   At best, this is a dupe of #213 which we will leave open in case someone ever feels like taking a crack at it.

**Closed by petersilva** 2019-06-08 05:30 UTC
Labels: invalid
