### ISSUE TITLE
Log rotation error on Windows

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#112] opened 2018-11-02 20:38 UTC
The problem came out from this case:

> sr_subscribe a roulé toute la nuit. Tous les fichiers RPDS10 demandés ont été téléchargés. Cependant, le fichier de log (en attachement) montre 2 choses importantes :
> ...
> 2) Le problème de log est encore apparu à 23:59 quand sr_subscribe a tenté de renommer le fichier de log et de repartir le log à 0. En utilisant l'outil Process Explorer de Windows, je vois que python.exe a 3 handles ouverts sur le fichier de log (voir attachement).  Est-il possible que ce soit la cause du problème (1 thread tente de renommer le fichier de log pendant que les 2 autres threads ont encore un handle ouvert sur le fichier)? On roule maintenant sans logging, mais les téléchargements continuent.
> 

with this config file:

> broker amqps://anonymous:anonymous@dd.weather.gc.ca
> subtopic model_gem_regional.10km.grib2.#
> 
> directory rainscan\remiTestSrSubscribe\downloadedFiles\rdps-2
> accept .\*CMC_reg_(TMP_TGL_2|WIND_TGL_10|WDIR_TGL_10|APCP_SFC_0|PRMSL_MSL_0)_ps10km_.\*\.grib2

at the time to rotate the log sarracenia threw up this trace and stopped behaving normally:

> Traceback (most recent call last):
> 
>   File "c:\python34\lib\logging\handlers.py", line 72, in emit
>     self.doRollover()
> 
>   File "c:\python34\lib\logging\handlers.py", line 393, in doRollover
>     self.rotate(self.baseFilename, dfn)
> 
>   File "c:\python34\lib\logging\handlers.py", line 113, in rotate
>     os.rename(source, dest)
> 
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Administrator\\AppData\\Local\\science.gc.ca\\sarra\\Logs\\sr_subscribe_Rdps10_01.log' -> 'C:\\Users\\Administrator\\AppData\\Local\\science.gc.ca\\sarra\\Logs\\sr_subscribe_Rdps10_01.log.2018-10-05'

**Comment by benlapETS** [comment] 2018-11-02 20:58
Here is some of the documentation i found on this on the internet:

- https://stackoverflow.com/questions/22459850/permissionerror-when-using-python-3-3-4-and-rotatingfilehandler

- an old python bug (the questionning in the issue): https://bugs.python.org/issue4749

**Comment by petersilva** [comment] 2018-11-03 04:48
sigh... it looks like we need to derive a class from the timedrotatinglog thing.. perhaps the following will work?:  always write logs with the date suffix, so we never have to rename them.

- override the rotate() method to do nothing (so we don't try to rename, and therefore don't get an error.)
- perhaps override rotation_filename to do nothing...
- override namer to always have have the current date in the log file name.

**Comment by petersilva** [comment] 2018-11-12 08:58
It turns out that the problem is not multiple processes accessing the same file, but the same file being opened with multiple file descriptors. On Linux, the logfile is re-opened twice to capture both standard error and standard output.  The three open file descriptors share writing to the log.

found a recipe here: https://www.electricmonk.nl/log/2011/08/14/redirect-stdout-and-stderr-to-a-logger-in-python/

to accomplish the same goal using python's logging mechanism, rather than system level i/o.
I think patch:  8711c59ebe0e003eae147cedd707da924eb2aee1

fixes this issue.

**Comment by petersilva** [comment] 2018-11-21 18:59
fix released in 2.18.11b1

**Closed by petersilva** 2018-11-21 18:59 UTC
Labels: likely-fixed
