### ISSUE TITLE
If sender does not succeed in posting a message after sending a file, it should retry.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#466] opened 2022-03-15 15:12 UTC
@habilinour suggested this...
when we are sending to a server,  we complete sending the file, but then need to publish the notification and that part fails... we should (optionally?) retry.

**Comment by petersilva** [comment] 2022-03-16 04:17
I just looked at the logic in sr3, and it's already implemented there afaict.  if the moth.putMessage( fails, then it gets put on the failed list, and the flowcb/retry module, perrsists that.  so across shutdown & restart, if there are pending posts, it should take care of it... I guess would have to test.

**Comment by petersilva** [comment] 2022-03-16 04:20
well the retry logic is there, but the logic in the MQP modules to return a failure isn't. I think for now it just locks up trying to post the message looping on re-connection forever. so there is still some work to do.

**Comment by petersilva** [comment] 2022-03-17 03:57
@reidsunderland  does this make sense to you? Can you run the flow tests? steps:
* not loop trying to re-connect in publish... putMessage needs to accept the connection is broken, and return False.
* the flowcb/retry.py module should take the resulting messages that failed to be published, and persist them to a retry file.
* on restart, when returning to publish, flowcb/retry already seems to add selections from the retry file to the publishing queue.
* It should perhaps simply attempt to connect once if not connected, and give up if it fails, rather than looping as it does today.

I think the key here is to start getting publish to return False, have the

**Comment by reidsunderland** [comment] 2022-03-18 21:20
`flowcb/retry.py` uses a callback, `after_post` that wasn't implemented. c468cbdc4b7dfbdf1f9089b8096aa63e356ac8a2 enables `after_post`.

> * not loop trying to re-connect in publish... putMessage needs to accept the connection is broken, and return False.

✔️ Forcing a return of False from `putNewMessage` does cause the message to be put in the list of failed messages.

> * the flowcb/retry.py module should take the resulting messages that failed to be published, and persist them to a retry file.

✔️ This works.

```
[DEBUG] sarracenia.diskqueue put DEBUG add to new file diskqueue_post_retry_000.new {'pubTime': '20220318T192459.258709192', 'relPath': '20200105/WXO-DD/bulletins/alphanumeric/20200105/UB/KMSC/02/UBUS01_KMSC_050200___26145', 'subtopic': ['20200105', 'WXO-DD', 'bulletins', 'alphanumeric', '20200105', 'UB', 'KMSC', '02'], 'baseUrl': 'http://localhost:8090', 'from_cluster': 'localhost', 'size': 596, 'mtime': '20220207200718.419902802', 'atime': '20220318192459.237973213', 'mode': '664', 'integrity': {'method': 'sha512', 'value': '/8rRNBOm4bncCEq1vYKYs1Q5TLl8eSUUyNcHxDyjAbA1Ag5tCZtPI4ZKTEeKvRyMjUW0PuY4Aq5rPW6bUA1qNg=='}, 'parts': '1,596,1,0,0', 'sum': 's,ffcad13413a6e1b9dc084ab5bd8298b354394cb97c792514c8d707c43ca301b035020e6d099b4f23864a4c478abd1c8c8d45b43ee63802ae6b3d6e9b500d6a36'}
```

> * on restart, when returning to publish, flowcb/retry already seems to add selections from the retry file to the publishing queue.

This part and/or the `DiskQueue` class seems to need more debugging.

https://github.com/MetPX/sarracenia/blob/7d52c0e3bd7d1324269da58e89be08b002611562/sarracenia/flowcb/retry.py#L81-L108

**Comment by reidsunderland** [comment] 2022-03-24 21:38
The DiskQueue class doesn't seem to be broken.

Currently, the main issue that needs to be resolved is that during the posts of the flakey test, the `on_housekeeping` callback of the retry plugin (and corresponding `on_housekeeping` of DiskQueue) never runs because the post processes cleanly exit before the housekeeping interval has elapsed. This means that messages are stuck in the `.new` file of the DiskQueue and never get processed.

There needs to be a way to not close here when there are messages in the retry queue, or `.new` file... https://github.com/MetPX/sarracenia/blob/835a0a0a4e28babd98d5757b6cb129bae6e210b0/sarracenia/flow/__init__.py#L384-L386

Or, maybe housekeeping should run before closing/some other way to check/sync/empty the retry queues?

**Comment by petersilva** [comment] 2022-03-25 02:19
so... the purpose of the retry_queue is so that when we shutdown, we can pick up where we left off.  That's why it is written to disk in the first place. So insisting the queue is empty will not work, for example when trying to do an orderly shutdown... we can't wait for the queues to be empty.  The point is for, on restart, it needs to read the queue from disk and try to complete them.

The flow test is not a normal case, because we want to be sure everything is done for metrics... in real life, we are fine with shutting down, as long as recovery occurs when starting up... hmm food for thought.

is the housekeeping stuff being called?

**Comment by reidsunderland** [comment] 2022-03-30 20:39
Finally, some progress! With the already committed bug fixes, the retry logic seems to be mostly working.

But, after the broker goes down, the AMQP class would be stuck in a state with a broken connection. This is similar to what we had already fixed in #407, where we had to `close` and re-`putSetup` the connection in `putNewMessage`. With retry in use, `putNewMessage` would fail to send the message, and correctly return False, before the existing calls to `close` and `__putSetup`.

I think we need to check if the connection is in a good state at the beginning of `putNewMessage` and try to reconnect if it's not. If the reconnect fails, it can immediately return False without wasting time trying to publish the message over a broken connection.

It seems like the connection status could be checked with (some combination of?) these conditions:

```python
if (self.connection is None) or (not self.connection.connected) or (not self.channel.is_open):
```

Where is the best place to call `close`? [Before `putNewMessage` returns False](https://github.com/MetPX/sarracenia/blob/b5294d50dbd5289f7b980ed05d4b2c320c51a272/sarracenia/moth/amqp.py#L584-L585), or at the beginning, immediately before calling `__putSetup`?

---

I also currently have retries disabled for post, and I'm just using the existing loop code. This is because the post closes cleanly due to it thinking it's finished everything it needs to do before the housekeeping interval expires. Based on the earlier discussion, I'm not sure what the best solution for this is...

It's likely that post could be run over and over, but none of the singular runs of post would ever execute for long enough for `on_housekeeping` to be triggered. So all the messages to be retried are permanently stuck in the `.new` file of the DiskQueue.

**Comment by petersilva** [comment] 2022-04-02 04:15
looks like great progress!

**Comment by petersilva** [comment] 2022-04-02 04:28
I'm wondering about the semantics of 'on_stop' ... I don't know exactly where it is called... I changed semantics of the exiting a  few commits ago.. ba3ce52decd15ae6bab49700dac4e45c7b3cbed4  added a 'please_stop' entry point, like you added an after_post. after a stop is requested, it does the main loop in run, but with no gather (no new worklist.incoming.) so it's a chance to empty out pending stuff.   That might be worth trying here?

Maybe we need to either:

* trigger the on_housekeeping processing with please_stop, and make sure that conditions are such that please_stop gets called... and it rolls over the new file before the last pass through the loop.

* do something similar with on_stop... but I think on_stop is called too late... it's just for cleanup at the very end... 

please_stop is at the beginning... perhaps a better name would be before_stop ?

**Comment by reidsunderland** [comment] 2022-04-07 18:47
After these changes, aa11f3e1e7bb6a7ed9cf0c01fd8be7be2043233b, things seem close to working, but some messages are getting stuck unacked in queues.

**Comment by MagikEh** [comment] 2022-05-02 17:36
Resolution of this issue may also fix #369

**Comment by reidsunderland** [comment] 2022-05-04 18:18
Summary of what needs to be done:

- Implement an option that will prevent a post from exiting while there are messages waiting to be retried in the DiskQueues. 
  - This applies to the flow tests, where the post only runs once and needs to keep trying to post messages until the broker comes back online.
  - Normally, a post would create messages and try to publish them. If publishing fails, the messages are saved to disk and the post exits. Messages would be loaded and retried whenever the poll is started next.
- Implement message counting in the DiskQueue class, so it knows how many messages are in the queue and `.new` files.
- Allow the DiskQueue class to report the number of messages in the queue back to the Flow class. 
  - Likely using something similar to how [metrics are done in the Moth classes](https://github.com/MetPX/sarracenia/blob/main/sarracenia/moth/__init__.py#L326-L327).

**Comment by reidsunderland** [comment] 2022-05-13 19:37
- Added the `retryEmptyBeforeExit` option.
- Added DiskQueue message counting, and reporting the number of messages back to Flow. 

Now when `retryEmptyBeforeExit` is set to True in the config files, and there are still messages remaining in the retry DiskQueues, posts will not exit until the messages have been successfully posted.

---

The problem with un-acked messages remains. When `putNewMessage` in moth/amqp.py is modified so that it returns False instead of looping when a message is not successfully published, `flow_limit.sh` of flakey_broker gets stuck because there are messages stuck in the queues.

![image](https://user-images.githubusercontent.com/4219654/168377685-3bc7f21d-5158-4198-bb7e-89abd5fd5cce.png)


![image](https://user-images.githubusercontent.com/4219654/168376409-a1a76c85-3275-46fa-a730-4ba3060fa817.png)

**Comment by petersilva** [comment] 2022-05-14 13:27
Great progress!

when you run this test, try going into the management interface... looking at one of the queus with unacked messages, and see if you can "get" the message so we can see which one it is, then search for the message in the corresponding log.  It looks like there is some path where the ack isn't generated.  Might be easier to find with some examples.  Otherwise we'll need to figure it out by guessing... which can work... just more work.

**Comment by reidsunderland** [comment] 2022-06-06 14:47
On one run, I got stuck with 23 messages un-acked: 

```
Still   23 messages (in queues: q_tfeed_sarra.download_f20.27604522.62311816, q_tsource_poll.sftp_f62.82740415.20533637, q_tsource_poll.sftp_f63.01400017.01642900, q_tsource_sender.tsource2send_f50.91541469.46998040, q_tsource_shovel.rabbitmqtt_f22.60722643.57646739, q_tsource_subscribe.cp_f61.31672021.64845310, q_tsource_subscribe.q_f71.59235477.41420887, q_tsource_subscribe.u_sftp_f60.51197070.42107815, q_tsub_subscribe.amqp_f30.05236628.72556146, q_tsub_subscribe.rabbitmqtt_f31.23466985.86518729) flowing, waiting...
```

![image](https://user-images.githubusercontent.com/4219654/172173413-62224bc9-4923-4c37-8483-306bceb1c2d6.png)

If I try to get the messages from the RabbitMQ web interface, it says "Queue is empty".

![image](https://user-images.githubusercontent.com/4219654/172184864-f29b711e-90a4-4615-be0e-e5cdd050487f.png)

<details><summary>The flow check results look good...</summary>

```
TEST RESULTS

                 | content of subdirs of /home/reid/sarra_devdocroot |
test 1 success: compare contents of downloaded_by_sub_amqp and downloaded_by_sub_cp are the same
test 2 success: compare contents of downloaded_by_sub_cp and downloaded_by_sub_rabbitmqtt are the same
test 3 success: compare contents of downloaded_by_sub_rabbitmqtt and downloaded_by_sub_u are the same
test 4 success: compare contents of downloaded_by_sub_u and posted_by_shim are the same
test 5 success: compare contents of posted_by_shim and sent_by_tsource2send are the same
test 6 success: compare contents of downloaded_by_sub_amqp and cfile are the same
test 7 success: compare contents of cfile and cfr are the same
                 | dd.weather routing |
test  8 success: expected 2242 number of extended attributes in source tree 2242
test  9 success: post	 count of posted files (1111) should be same those in the static data directory	 (1111)
test 10 success: post	 count of rejected files (10) should be same those in the static data directory	 (10)
test 11 success: post	 (1111) t_dd1 should have the same number of items as t_dd2	 (1111)
test 12 success: sarra	 (1111) should have the same number of items as one post	 (1111)
test 13 success: sarra	 (1111) should winnow the same number of items as one post	 (1111)
test 14 success: subscribe amqp_f30	 (1111) should have the same number of items as sarra		 (1111)
                 | watch      routing |
test 15 success: watch		 (1111) should be the same as subscribe amqp_f30		  (1111)
test 16 success: sender		 (1111) should have the same number of items as watch  (1111)
test 17 success: rabbitmqtt		 (1111) should have the same number of items as watch  (1111)
test 18 success: subscribe u_sftp_f60 (1111) should have the same number of items as sender (1111)
test 19 success: subscribe cp_f61	 (1111) should have the same number of items as sender (1111)
                 | poll       routing |
test 20 success: poll sftp_f62	 (1111) should have the same number of items of sender	 (1111)
test 21 success: poll sftp_f63	 (1111) should see the same number of items as poll sftp_f62 posted	 (1111)
test 22 success: subscribe q_f71	 (1111) should have the same number of items as poll sftp_f62 (1111)
                 | flow_post  routing |
test 23 success: post test2_f61	 (1111) should have the same number of items of sender 	 (1111)
test 24 success: subscribe ftp_f70	 (1111) should have the same number of items as post test2_f61 (1111)
test 25 success: post test2_f61	 (1111) should have about the same number of items as shim_f63	 (1111)
                 | py infos   routing |
test 26 success: 0 messages received that we don't know what happened.
                 | C          routing |
test 27 success: cpost both pelles should post the same number of messages (1111) (1111)
test 28 success: cpost both pelles should see same amount of post_rate_limit messages (221) (221)
test 29 success: cpost pelle04 should post 5 times the number of post_rate_limit messages (1111) (221)
test 30 success: cdnld_f21 subscribe downloaded (1111) the same number of files that was published by both van_14 and van_15 (1111)
test 31 success: veille_f34 should post as many files (1111) as subscribe cdnld_f21 downloaded (1111)
test 32 success: veille_f34 should post as many files (1111) as subscribe cfile_f44 downloaded (1111)
test 33 success: Overall 32 of 32 passed (sample size: 1111) !
```

</details>

**Comment by reidsunderland** [comment] 2022-06-07 17:56
Messages that are retrieved from the post retry DiskQueue have `isRetry: True` added to the messages. This seems to be the cause of the unacked messages.

I assume because the re-posted message is not exactly the same, the re-posted message is consumed and acked correctly, and the original message that does not have `isRetry: True` gets stuck as an un-acked message.

@petersilva, do we need to send the `isRetry` part of the message? It seems to work properly if `isRetry` is added to `_deleteOnPost`.

**Comment by petersilva** [comment] 2022-06-07 19:20
yeah, should add isRetry to the message before saving it to the queue.

**Comment by reidsunderland** [comment] 2022-06-07 20:28
Discussed with @petersilva, and the issue is not caused by sending a message containing `isRetry`, the problem is with how the subscriber handles the message when it's received.

This code does not send an ack for all messages with `isRetry: True`: 

https://github.com/MetPX/sarracenia/blob/0362371adc05c110e122c9224c6f941da26661c0/sarracenia/flowcb/gather/message.py#L37-L41

The intent was to prevent the consumer from re-acking a message it needs to retry downloading which is the correct behavior for messages in case **ii.** below. But the consumer **does** need to ack a message that needed to be retried when posted (case **i.**).

The fix seems to be removing the if statement. Case ii. messages will continue to not be re-acked, because they will have the `ack_id` removed by the [DiskQueue class](https://github.com/MetPX/sarracenia/blob/0362371adc05c110e122c9224c6f941da26661c0/sarracenia/diskqueue.py#L206-L208).

---

This is my understanding of what is happening in the flakey broker test to cause un-acked messages in the queues:

1. When the broker goes down:
    1. **Publisher:** Some messages fail to post, and these are put into the post-retry DiskQueue. 
    2. **Subscriber:** Some (different) messages that were already successfully posted to the broker fail to be downloaded by the subscriber and are put into the download-retry DiskQueue (these aren't directly relevant to the un-acked messages issue).
        - These messages should not be re-acked when retrieved from the download-retry DiskQueue.
2. When the broker recovers, the publisher re-posts messages from the post-retry DiskQueue (i.). These messages are posted with the `isRetry: True` property. The subscriber receives these messages, processes them, but *never sends an ack to the broker* because of the code above. This causes the messages to get stuck in the queues as un-acked.

**Comment by petersilva** [comment] 2022-06-08 16:10
Great work! so when posting messages, we need to make sure isRetry is removed... somehow that is not happenning.

**Comment by reidsunderland** [comment] 2022-06-08 16:31
Because messages that should not be re-acked (ones being downloaded again) will have their `ack_id` deleted by the DiskQueue class, so that if statement wasn't necessary to prevent re-acking re-downloaded messages.

If the message has no ack_id, moth's ack method will do nothing and return:

https://github.com/MetPX/sarracenia/blob/b5294d50dbd5289f7b980ed05d4b2c320c51a272/sarracenia/moth/amqp.py#L438-L448

**Comment by petersilva** [comment] 2022-06-08 22:19
agreed... but the problem is caused... from what you have written...  because we publish messages with isRetry set in them... which, when initially received is wrong... no message should have isRetry set on receipt. or be transmitted containing the field.  I agree with the fix so far, but the stuff you found raises three choices:

* leave isRetry as-is, where it gets included in messages and transmitted ... kind of bogusly... 
* Delete isRetry entirely (does it serve any purpose at all?) so that it doesn't get bogusly tranmitted.
* fix isRetry so that it is removed before retransmission/posting because a posted message should not have that value set.

I think we currently have the first option, I think one of the latter two is cleaner, but not sure which to pick among them.

**Comment by petersilva** [comment] 2022-06-08 22:24
* The middle option means looking up lines where 'isRetry' is mentioned, and removing them.
except when dealing with v2... not sure what needs to be done.

* last option boils down to adding:
```
    m['_deleteOnPost'] |= set(['isRetry'])

```
somewhere... dunno where.

**Comment by reidsunderland** [comment] 2022-06-09 13:35
I thought isRetry was supposed to be transmitted with the messages, even though it's not currently used. Since it's not supposed to be sent, then I agree with the options

> - Delete isRetry entirely (does it serve any purpose at all?) so that it doesn't get bogusly tranmitted.
> - fix isRetry so that it is removed before retransmission/posting because a posted message should not have that value set.

DiskQueue is where `isRetry` is added and set to true, maybe that should be where `isRetry` is added to `_deleteOnPost`?

https://github.com/MetPX/sarracenia/blob/aa282dce71e081387daf953f3c5cbf0a17c30db6/sarracenia/diskqueue.py#L205

**Comment by petersilva** [comment] 2022-06-09 13:44
yup. that looks like it!

**Comment by reidsunderland** [comment] 2022-06-10 18:13
@petersilva and I decided to remove `isRetry`, because it's mostly un-used code. 

A plugin, testretry, did make use of `isRetry`, but the plugin hasn't been used in a long time. #527 has been opened to update the plugin and re-implement retry testing in dynamic flow tests, but this can be done without `isRetry`.

**Comment by petersilva** [comment] 2022-06-10 18:15
Great! so I guess it now actually passes all of the flow tests?

**Comment by petersilva** [comment] 2022-06-27 14:50
@reidsunderland is this nearly done? I lost track.

**Comment by reidsunderland** [comment] 2022-06-27 18:58
Yes, it passes all the flow tests as well as v03_wip does... so flakey still has errors with the polls, but it's unrelated to these changes.

<details><summary>Test Results</summary>

```
		TEST RESULTS

                 | content of subdirs of /home/reid/sarra_devdocroot |
test 1 success: compare contents of downloaded_by_sub_amqp and downloaded_by_sub_cp are the same
test 2 success: compare contents of downloaded_by_sub_cp and downloaded_by_sub_rabbitmqtt are the same
test 3 success: compare contents of downloaded_by_sub_rabbitmqtt and downloaded_by_sub_u are the same
test 4 success: compare contents of downloaded_by_sub_u and posted_by_shim are the same
test 5 success: compare contents of posted_by_shim and sent_by_tsource2send are the same
test 6 success: compare contents of downloaded_by_sub_amqp and cfile are the same
test 7 success: compare contents of cfile and cfr are the same
                 | dd.weather routing |
test  8 success: expected 2242 number of extended attributes in source tree 2242
test  9 success: post	 count of posted files (1111) should be same those in the static data directory	 (1111)
test 10 success: post	 count of rejected files (10) should be same those in the static data directory	 (10)
test 11 success: post	 (1111) t_dd1 should have the same number of items as t_dd2	 (1111)
test 12 success: sarra	 (1111) should have the same number of items as one post	 (1111)
test 13 success: sarra	 (1111) should winnow the same number of items as one post	 (1111)
test 14 success: subscribe amqp_f30	 (1111) should have the same number of items as sarra		 (1111)
                 | watch      routing |
test 15 success: watch		 (1111) should be the same as subscribe amqp_f30		  (1111)
test 16 success: sender		 (1111) should have the same number of items as watch  (1111)
test 17 success: rabbitmqtt		 (1111) should have the same number of items as watch  (1111)
test 18 success: subscribe u_sftp_f60 (1111) should have the same number of items as sender (1111)
test 19 success: subscribe cp_f61	 (1111) should have the same number of items as sender (1111)
                 | poll       routing |
test 20 FAILURE: poll sftp_f62	 (1556) should have the same number of items of sender	 (1111)
test 21 FAILURE: poll sftp_f63	 (555) should see the same number of items as poll sftp_f62 posted	 (1556)
test 22 FAILURE: subscribe q_f71	 (1111) should have the same number of items as poll sftp_f62 (1556)
                 | flow_post  routing |
test 23 success: post test2_f61	 (1111) should have the same number of items of sender 	 (1111)
test 24 success: subscribe ftp_f70	 (1111) should have the same number of items as post test2_f61 (1111)
test 25 success: post test2_f61	 (1111) should have about the same number of items as shim_f63	 (1111)
                 | py infos   routing |
test 26 success: 0 messages received that we don't know what happened.
                 | C          routing |
test 27 success: cpost both pelles should post the same number of messages (1111) (1111)
test 28 success: cpost both pelles should see same amount of post_rate_limit messages (221) (220)
test 29 success: cpost pelle04 should post 5 times the number of post_rate_limit messages (1111) (221)
test 30 success: cdnld_f21 subscribe downloaded (1111) the same number of files that was published by both van_14 and van_15 (1111)
test 31 success: veille_f34 should post as many files (1111) as subscribe cdnld_f21 downloaded (1111)
test 32 success: veille_f34 should post as many files (1111) as subscribe cfile_f44 downloaded (1111)
test 33 FAILURE: Overall 29 of 32 passed (sample size: 1111) !
```

</details>

The missing piece was telling Sarracenia to use the DiskQueue. Instead of looping infinitely, `putNewMessage` needs to return False and have `flowcb/post/message.py` put the message into `worklist.failed`:

https://github.com/MetPX/sarracenia/blob/4c9a4c8455a7678fd4ae11149b21438708661013/sarracenia/flowcb/post/message.py#L39-L47

---

Ideally, it would be possible to configure whether a loop is used ("stubborn") or the retry DiskQueues (not "stubborn"). Provisions exist in amqp.py for `message_strategy['stubborn']` to be used to control whether or not putNewMessage loops or returns False...

https://github.com/MetPX/sarracenia/blob/4c9a4c8455a7678fd4ae11149b21438708661013/sarracenia/moth/amqp.py#L546-L547

... but `message_strategy['stubborn']` is also checked in `__putSetup`, `__getSetup` and `getNewMessage` and it does not work correctly there. 

A new issue, #537 has been opened to get `message_strategy['stubborn']` working, but for now, the check has been commented out and the loop in `putNewMessage` has been disabled, so it will always return False and use the DiskQueues to retry when there's an error.

https://github.com/MetPX/sarracenia/blob/e1d5de42cf6d05ccd4a098c0f92d2fe988689f39/sarracenia/moth/amqp.py#L546-L551

**Closed** 2022-07-11 18:11 UTC
Labels: enhancement, likely-fixed, Priority 5  - Defect, v3only
